"use client";
import { Eye, EyeOff } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { AuthAppBar } from "@/components/layout/auth-app-bar";
import { ActionButton } from "@/components/ui/action-button";
import { FormField } from "@/components/ui/form-field";
import { ROUTES } from "@/config/routes";
import { useLoginMutation, useSignupMutation } from "@/features/auth/mutations";

export function ParentLogin() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const mutation = useLoginMutation();
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await mutation.mutateAsync({ role: "parent", loginId: email, password }); router.push(ROUTES.parent.home); } catch { return; } };
  return <div className="min-h-dvh bg-app"><AuthAppBar title="학부모 로그인" action={{ label: "도움말" }} /><main className="space-y-4 p-5"><section className="relative overflow-hidden rounded-2xl bg-brand p-5 text-[#4C3024]"><span className="absolute -right-8 -top-8 size-28 rounded-full bg-white/25" /><p className="text-[11px] font-bold tracking-[0.08em]">PARENT LOGIN</p><h2 className="mt-2 text-[22px] font-extrabold">자녀의 성장을 한눈에</h2><p className="mt-1 text-sm leading-6 text-[#694838]">학습기록과 월별 보고서를 확인하세요.</p></section><form onSubmit={submit} className="space-y-3 rounded-card border border-border bg-surface p-5"><FormField label="이메일" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="parent@example.com" /><FormField label="비밀번호" type={show ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="비밀번호를 입력하세요" trailing={<button type="button" onClick={() => setShow((value) => !value)} className="grid size-8 place-items-center text-subtle">{show ? <EyeOff size={18} /> : <Eye size={18} />}</button>} />{mutation.isError ? <p className="text-xs font-semibold text-[#D64545]">로그인에 실패했습니다. 입력 정보를 확인해 주세요.</p> : null}<ActionButton type="submit" disabled={!email || !password || mutation.isPending}>{mutation.isPending ? "로그인 중..." : "로그인"}</ActionButton><Link href={ROUTES.auth.parentSignup} className="flex h-[52px] items-center justify-center rounded-xl border border-[#A9D4F2] text-sm font-bold text-[#2F6FA7]">학부모 회원가입</Link><p className="pt-1 text-center text-xs text-subtle">이메일 찾기 · 비밀번호 재설정</p></form></main></div>;
}

export function ParentSignup() {
  const router = useRouter(); const [agreed, setAgreed] = useState(false); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const mutation = useSignupMutation();
  const signup = async () => { try { await mutation.mutateAsync({ role: "parent", name, email, password }); router.push(ROUTES.parent.home); } catch { return; } };
  return <div className="min-h-dvh bg-app"><AuthAppBar title="학부모 회원가입" backHref={ROUTES.auth.parentLogin} /><main className="space-y-4 p-5"><div className="flex gap-2" aria-label="회원가입 진행 단계"><span className="h-1 flex-1 rounded-full bg-brand" /><span className={`h-1 flex-1 rounded-full ${name ? "bg-brand" : "bg-[#E3E7ED]"}`} /><span className={`h-1 flex-1 rounded-full ${email && password ? "bg-brand" : "bg-[#E3E7ED]"}`} /></div><section className="space-y-3 rounded-card border border-border bg-surface p-5"><h2 className="text-lg font-bold">계정 정보 입력</h2><FormField label="이름" value={name} onChange={(event) => setName(event.target.value)} placeholder="학부모 이름" /><FormField label="이메일" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="parent@example.com" /><FormField label="비밀번호" type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="8자 이상 입력" /><label className="flex items-start gap-3 rounded-xl bg-app p-3 text-sm"><input type="checkbox" checked={agreed} onChange={(event) => setAgreed(event.target.checked)} className="mt-0.5 size-5 accent-[#D96534]" /><span>서비스 이용약관 및 개인정보 수집·이용에 동의합니다.</span></label>{mutation.isError ? <p className="text-xs font-semibold text-[#D64545]">회원가입을 완료하지 못했습니다. 다시 시도해 주세요.</p> : null}<ActionButton disabled={!agreed || !name || !email || password.length < 8 || mutation.isPending} onClick={signup}>{mutation.isPending ? "가입 처리 중..." : "가입 완료하고 시작하기"}</ActionButton></section><p className="text-center text-xs leading-5 text-muted">학부모 계정은 가입 즉시 이용할 수 있으며<br />내 정보에서 자녀를 등록할 수 있습니다.</p></main></div>;
}
