import type { ParentAnalysisResponse, ParentNotification, ParentProfileResponse, ParentRecord, ParentReport } from "@/features/parent/model/types";

export const parentRecords: ParentRecord[] = [
  { id: "l1", date: "08.18", month: "2026-08", area: "화법과작문", title: "화법과작문 실전 모의", questionCount: 15, accuracy: 73, elapsed: "28:15", wrongCount: 3, trend: [{ label: "7/28", accuracy: 52 }, { label: "8/4", accuracy: 60 }, { label: "8/11", accuracy: 67 }, { label: "8/18", accuracy: 73 }], detail: { totalTime: "28분 15초", wrongTypeSummary: "추론형 2문항, 표현형 1문항", overtimeQuestionSummary: "3, 7번 문항", baselineAccuracy: 61, correctCount: 12, reviewCount: 3, repeatedMistakeCount: 1, insight: "사실 확인은 안정적이지만 비판·평가에서 같은 범위 혼동이 반복됐어요.", skillResults: [{ skill: "사실 확인", accuracy: 82, questionCount: 11, status: "stable" }, { skill: "비판·평가", accuracy: null, questionCount: 4, status: "insufficient" }] } },
  { id: "l2", date: "08.15", month: "2026-08", area: "언어·매체", title: "언어와 매체 핵심유형", questionCount: 12, accuracy: 58, elapsed: "24:40", wrongCount: 5, trend: [{ label: "7/25", accuracy: 49 }, { label: "8/1", accuracy: 55 }, { label: "8/8", accuracy: 61 }, { label: "8/15", accuracy: 58 }], detail: { totalTime: "24분 40초", wrongTypeSummary: "문법형 3문항, 매체형 2문항", overtimeQuestionSummary: "4, 9번 문항", baselineAccuracy: 61, correctCount: 7, reviewCount: 5, repeatedMistakeCount: 2, insight: "개념·지식에서 용어를 혼동한 기록이 반복되어 다음 학습에서 먼저 확인할 필요가 있어요.", skillResults: [{ skill: "개념·지식", accuracy: 50, questionCount: 10, status: "weak" }, { skill: "사실 확인", accuracy: null, questionCount: 2, status: "insufficient" }] } },
  { id: "l3", date: "08.12", month: "2026-08", area: "독서", title: "독서 비문학 빠른 독해", questionCount: 10, accuracy: 80, elapsed: "19:22", wrongCount: 2, trend: [{ label: "7/22", accuracy: 58 }, { label: "7/29", accuracy: 65 }, { label: "8/5", accuracy: 72 }, { label: "8/12", accuracy: 80 }], detail: { totalTime: "19분 22초", wrongTypeSummary: "추론형 2문항", overtimeQuestionSummary: "없음", baselineAccuracy: 61, correctCount: 8, reviewCount: 2, repeatedMistakeCount: 0, insight: "사실 확인과 추론 모두 자기 기준선보다 높았고, 시간 초과 없이 안정적으로 풀었어요.", skillResults: [{ skill: "독해 종합", accuracy: 80, questionCount: 10, status: "stable" }] } },
  { id: "l4", date: "08.08", month: "2026-08", area: "문학", title: "현대시 독해 집중훈련", questionCount: 10, accuracy: 70, elapsed: "20:05", wrongCount: 3, trend: [{ label: "7/18", accuracy: 50 }, { label: "7/25", accuracy: 57 }, { label: "8/1", accuracy: 64 }, { label: "8/8", accuracy: 70 }], detail: { totalTime: "20분 5초", wrongTypeSummary: "표현형 2문항, 개념형 1문항", overtimeQuestionSummary: "6번 문항", baselineAccuracy: 61, correctCount: 7, reviewCount: 3, repeatedMistakeCount: 1, insight: "표현상 특징은 개선됐지만 개념 적용 문항은 기록을 더 모아 확인해야 해요.", skillResults: [{ skill: "현대시 독해 종합", accuracy: 70, questionCount: 10, status: "stable" }] } },
];

export const accuracyTrend = [
  { label: "7/28", accuracy: 52 }, { label: "8/4", accuracy: 60 }, { label: "8/11", accuracy: 67 }, { label: "8/18", accuracy: 73 },
];

export const areaScores = [
  { area: "언어", score: 63 }, { area: "매체", score: 56 }, { area: "문학", score: 59 }, { area: "독서", score: 43 }, { area: "화법과작문", score: 71 },
];

const reportPdf = { url: "/reports/CheckOn-parent-report-2026-08.pdf", pageImageBasePath: "/reports/pages/report-", pageLabels: ["표지", "월간 분석", "선생님 의견", "주간 분석", "영역·유형별 성과", "진단 결과", "영역별 성취도"] };
export const parentReports: ParentReport[] = [
  { id: "r1", year: 2026, month: 8, studentName: "김민준", teacher: "박지은 선생님", pages: 7, issuedAt: "2026.08.19", isNew: true, studyPeriod: "2026.08.01 ~ 08.18", summary: { accuracy: 68, weaknessImprovement: 12, priorityArea: "독서", comparisonMonth: "2026년 7월", gradedQuestionCount: 37, repeatedMistakeCount: 5 }, teacherComment: "독서 개념·지식 유형은 지난달보다 개선됐지만, 범위 혼동이 반복되고 있습니다. 다음 달에는 짧은 보완 학습을 주 1회 배치하겠습니다.", sections: [{ title: "월간 분석", description: "정답률·채점 문항·약점 개선 흐름", status: "available" }, { title: "선생님 의견", description: "기록에 근거한 학습 요약과 다음 달 제안", status: "available" }, { title: "주간 분석", description: "4주 정답률·다시 볼 문항·반복 실수", status: "available" }, { title: "영역·유형별 성과", description: "문항 수가 충분한 유형만 판정", status: "available" }, { title: "약점 연결 흐름", description: "함께 막힌 유형과 근거 기록", status: "available" }, { title: "영역별 성취도", description: "자기 평균을 기준으로 한 영역 비교", status: "available" }], pdf: reportPdf },
  { id: "r2", year: 2026, month: 7, studentName: "김민준", teacher: "박지은 선생님", pages: 7, issuedAt: "2026.07.20", isNew: false, studyPeriod: "2026.07.01 ~ 07.18", summary: { accuracy: 64, weaknessImprovement: 9, priorityArea: "언어·매체", comparisonMonth: "2026년 6월", gradedQuestionCount: 42, repeatedMistakeCount: 7 }, teacherComment: "언어·매체의 개념 혼동이 줄고 있습니다. 같은 유형을 짧게 반복하며 안정화를 이어가겠습니다.", sections: [{ title: "월간 분석", description: "정답률·채점 문항·약점 개선 흐름", status: "available" }, { title: "선생님 의견", description: "기록에 근거한 학습 요약과 다음 달 제안", status: "available" }, { title: "주간 분석", description: "4주 정답률·다시 볼 문항·반복 실수", status: "available" }], pdf: reportPdf },
  { id: "r3", year: 2026, month: 6, studentName: "김민준", teacher: "박지은 선생님", pages: 6, issuedAt: "2026.06.19", isNew: false, studyPeriod: "2026.06.01 ~ 06.17", summary: { accuracy: 61, weaknessImprovement: 7, priorityArea: "문학", comparisonMonth: "2026년 5월", gradedQuestionCount: 31, repeatedMistakeCount: 8 }, teacherComment: "문학 개념을 지문에 적용하는 과정에서 실수가 반복됐습니다. 근거 문장을 먼저 표시하는 연습을 진행하겠습니다.", sections: [{ title: "월간 분석", description: "정답률·채점 문항·약점 개선 흐름", status: "available" }, { title: "선생님 의견", description: "기록에 근거한 학습 요약과 다음 달 제안", status: "available" }, { title: "영역·유형별 성과", description: "일부 유형은 문항 수 부족으로 판단 보류", status: "insufficient" }], pdf: reportPdf },
];

export const parentAnalysis: ParentAnalysisResponse = {
  accuracy: 68, baselineAccuracy: 61, weaknessImprovement: 12, comparisonMonth: "2026년 7월", analysisAsOf: "2026.08.31", gradedQuestionCount: 37, reviewQuestionCount: 11, repeatedMistakeCount: 5, areaScores, accuracyTrend,
  weeklySummary: [{ label: "1주", accuracy: 52, questionCount: 8, reviewCount: 4, repeatedMistakes: null }, { label: "2주", accuracy: 60, questionCount: 11, reviewCount: 4, repeatedMistakes: 2 }, { label: "3주", accuracy: 67, questionCount: 8, reviewCount: 3, repeatedMistakes: null }, { label: "4주", accuracy: 73, questionCount: 10, reviewCount: 2, repeatedMistakes: 1 }],
  difficultyDistribution: [{ level: "하", count: 8 }, { level: "중", count: 21 }, { level: "상", count: 8 }],
  weaknessRanking: [{ rank: 1, area: "독서", skill: "개념·지식", accuracy: 43, questionCount: 12, gapFromBaseline: -18, status: "confirmed" }, { rank: 2, area: "언어·매체", skill: "개념·지식", accuracy: 48, questionCount: 10, gapFromBaseline: -13, status: "confirmed" }, { rank: 3, area: "문학", skill: "비판·평가", accuracy: 50, questionCount: 7, gapFromBaseline: -11, status: "watch" }],
  misconceptionSummary: [{ area: "독서", label: "범위 혼동", count: 3 }, { area: "언어·매체", label: "개념 혼동", count: 2 }],
  primaryWeakness: { area: "독서", skill: "개념·지식", score: 43, description: "최근 4주 집중 보완 필요", studyFrequency: "주 1~2회 (비중 낮음)", averageTime: "문항당 3.2분 (전체 평균 2.1분)", evidenceQuestionCount: 12, previousMonthScore: 31, repeatedMistakeCount: 3, misconception: "범위 혼동", linkedWeaknesses: [{ label: "독서 · 사실 확인", relationScore: 72 }, { label: "문학 · 비판·평가", relationScore: 58 }], nextAction: "주 1회 10문항 내외의 짧은 보완 학습으로 개념 적용과 근거 범위를 함께 확인합니다.", relatedRecordId: "l3" },
};

export const parentProfile: ParentProfileResponse = { id: "parent-1", name: "이순영", maskedPhone: "010-XXXX-5678", notificationsEnabled: true, children: [{ id: "student-1", studentId: "STU-A41C", name: "김민준", grade: "고2", active: true }], teachers: [{ id: "teacher-1", name: "박지은 선생님", academy: "한울국어학원" }] };

export const parentNotifications: ParentNotification[] = [
  { id: "notification-1", type: "report", title: "8월 월별 보고서가 도착했어요", body: "박지은 선생님이 김민준 학생의 보고서를 발행했습니다.", createdAt: "오늘 14:20", read: false, href: "/parent/reports/r1" },
  { id: "notification-2", type: "learning", title: "이번 주 학습이 완료됐어요", body: "화법과작문 실전 모의 정답률은 73%입니다.", createdAt: "8월 18일", read: false },
];
